### PR TITLE
(#559) Profiler clean-up.

### PR DESCRIPTION
**Pull request by SolarLune**

### CODE REVIEW

**Comment by SolarLune** [comment]
Oops, missed the # to tie the issue and PR together.

(#559) Profiler clean-up.

**Comment by rafcolson** [comment]
Thanks. But I think you could leave out a couple of "start" 's. It should be enough to add ```Bdx.profiler.stop(subSystem);```. The "start" will be the last stop time as being documented in the Profiler's API.

**Comment by SolarLune** [comment]
Y'know, I tried that, but I was getting some weird results when I didn't; for example, Outside was getting negative values, and the percentages weren't adding up to 100%.

**Comment by rafcolson** [comment]
You can do this only with subsystems that aren't added yet. I suppose this should work in any occasion so I'll try to fix that later.

**Comment by SolarLune** [comment]
Oh, that might've explained it. Thanks for the info!

**Comment by GoranM** [comment]
Branch has conflicts. Please rebase from master.

**Comment by SolarLune** [comment]
OK, that should do it.

**Pull request merged**
