### PR TITLE
Added subimage() getter and setter to SpriteAnim.

### PR DESCRIPTION
**Pull request by SolarLune**
Added playHead() getter and setter to be able to modify the playHead of the current animation.
Cleaned up imports a bit.

### CODE REVIEW

**Comment by GoranM** [comment]
I'm not sure about "subimage" as a name - I mean, you're changing the frame, so it would make more sense to have methods like:

```java
public int frame();
public void frame(int frame);
```

Wouldn't it?

**Comment by SolarLune** [comment]
There's already a frame() function in SpriteAnim.java. To avoid confusion, I think it might be best to avoid naming it "frame()" (or name the frame() function something else).

**Comment by GoranM** [comment]
The currently existing "frame" functions are private, and deal exclusively with Vectors. Even internally, type context makes the distinction quite clear (not to mention that it's enforced by the compiler); it's a complete non-issue externally, because users can't access private functions.

**Comment by SolarLune** [comment]
OK, I would change it, then, but we can't have two frame() getters.

**Comment by GoranM** [comment]
Oh, I just assumed that Java could distinguish between frame() - int and frame() - Vector2f, but I guess not ...

Anyway: It would probably be best to rename private frame methods to uvFrame, so we can just use frame for both public methods.

**Comment by SolarLune** [comment]
Done!

**Comment by GoranM** [comment]
Ok, looks good.

Thanks.

**Pull request merged**
