### PR TITLE
Access to Blender Game Properties through GameObject.props

### PR DESCRIPTION
**Pull request by rafcolson**
I'll update the API as soon as it's merged. Thanks for your help on this, Goran.

### CODE REVIEW

**Comment by GoranM** [comment]
Looks good.

Thanks!

**Comment by rafcolson** [comment]
Unfortunately there seems to be an issue with my build. I don't know if I'm doing something wrong, but when I'm building an *.apk I'm getting an exception. With v0.0.76 everything works fine, so it must have something to do with the commits regarding GameObject.props.

**Comment by GoranM** [comment]
There's nothing in your commits that could possibly break android builds - I just tested it, and it works fine on my system.

Did you remember to recompile bdx by running ant? Did you create a brand new project to test?

If you answered yes to questions above, try doing this for BDX:

```
ant clean
ant
```

And then for the project:

```
gradlew clean
gradlew android:assembleDebug
```

**Comment by SolarLune** [comment]
@rafcolson - Is this working? No matter what and where I put it, props.has("property name") always makes BDX crash with a null pointer exception...? Printing out the value of "props" just returns null.

**Comment by rafcolson** [comment]
>There's nothing in your commits that could possibly break android builds - I just tested it, and it works fine on my system.

That's reassuring. Thanks for the pointers, I'll try if that helps.

**Comment by GoranM** [comment]
It would help if you could describe your overall development setup, and the step by step procedure you follow to test your BDX changes.

**Pull request merged**
