### PR TITLE
(#763) - Add Descriptor to Input.

### PR DESCRIPTION
**Pull request by SolarLune**

### CODE REVIEW

**Comment by GoranM** [comment]
Conceptually, the descriptor is a string that describes the device, and the corresponding input on that device, so I think it would be a bit confusing to expose "descriptor" as a field that references a string array.

A string array would represent a descriptor in its parsed form, so if you want to expose that, I think something like "parsed_descriptor" would be a more suitable name.

Although, I'm not sure if parsed_descriptor should be a variable element array: It doesn't fit with the aforementioned "device:input" concept (which is fundamentally a 2 element thing), and it doesn't really offer a greater convenience (checking for the length of the array is no less difficult than checking the first element). So, with that in mind, I think it would make sense to just do:

```java
this.parsed_descriptor = d;
```

**Comment by SolarLune** [comment]
> Conceptually, the descriptor is a string that describes the device, and the corresponding input on that device, so I think it would be a bit confusing to expose "descriptor" as a field that references a string array.

Oh, so basically if anything, it should be the same descriptor that was passed to create the Input in the first place. I suppose so; maybe `parsedDescriptor` would be better? 

> It doesn't fit with the aforementioned "device:input" concept (which is fundamentally a 2 element thing)

Well, gamepads have IDs, so "g0:a" isn't the same as "g1:a"; do you mean that the descriptor should be, for example, `"g0", "a"` for a gamepad descriptor of "g:a" or "g0:a"?

> So, with that in mind, I think it would make sense to just do:

So it shouldn't add the ID of the gamepad as the second element of the descriptor, but just have it as part of the first element of the String array?

P.S. I think camelCase is the more Java-oriented naming convention?

**Comment by GoranM** [comment]
Yes.

**Comment by SolarLune** [comment]
OK, PR updated.

**Comment by SolarLune** [comment]
Wait, hold up, something's off with that `gpIndex` final at the end...

**Comment by SolarLune** [comment]
OK, that should do it. PR's good to go.

**Comment by SolarLune** [comment]
PR was merged, so I'll go ahead and close this. Thanks!

**Pull request merged**
