### PR TITLE
valid() check to prevent logic execution on invalidated objects (#125).

### PR DESCRIPTION
**Pull request by SolarLune**

### CODE REVIEW

**Comment by GoranM** [comment]
Your indentation is a bit off - It may not be visible in your editor, but it's obvious if you view the commit source here, on github.

Also, no need for that comment; The code itself is pretty simple/clear.

**Comment by SolarLune** [comment]
Fixed.

**Comment by GoranM** [comment]
The unnecessary comment is still there.

The commit message is not sufficiently descriptive (the one you used before was fine).

**Comment by SolarLune** [comment]
I don't know what you mean "the unnecessary comment", then. 

Oh, you mean the actual comment in the code. I'll fix it in awhile.

**Comment by SolarLune** [comment]
Fixed.

**Pull request merged**
