### PR TITLE
(#306) GameObject.mass setter and getter

### PR DESCRIPTION
**Pull request by rafcolson**

### CODE REVIEW

**Comment by GoranM** [comment]
It may be better to call the field `lastNonZeroMass`, to hint that we don't actually use this to store current mass.

**Comment by rafcolson** [comment]
Okay. Done. I also could reduce some lines by using the mass setter.

**Comment by GoranM** [comment]
The commit name doesn't make sense:

You're not "implementing lastNonZeroMass - That was simply a field you added as part of the setter getter commit.

The second commit should be named something that actually describes the changes.

In this case: "GameObject.dynamic now uses newly added mass methods"

**Comment by rafcolson** [comment]
Done.

**Pull request merged**
