### PR TITLE
Added Collision group & mask data to rigidbody

### PR DESCRIPTION
**Pull request by Nananas**
I added this collision data to the `GameObject`. Don't know if this is really necessary...

When changing the group or mask, the `Rigidbody` should be re-added to the scene. -> Todo?

### CODE REVIEW

**Comment by GoranM** [comment]
> When changing the group or mask, the Rigidbody should be re-added to the scene. -> Todo?

Is that all it takes? If you can make that work, and it tests fine, then I would include it, but I don't think it's a good idea to have additional GameObject methods if they don't do anything.

For now, it would probably be best to focus on just exporting and applying initially defined group/mask settings from blender (no need to change anything in GameObject until you can actually get it to work).

About your export code:

Is there a reason why `mask` is a negative number? I mean, in the [bullet documentation](http://www.bulletphysics.org/mediawiki-1.5.8/index.php?title=Collision_Filtering), there seems to be no such requirement - both bit fields are positive numbers.

Instead of extra variables, and multi-line loops, you could derive the bit field value like this:

```python
"group": sum([2**i for i, v in enumerate(obj.game.collision_group) if v])
```

It's less code, while being no less clear.

**Comment by Nananas** [comment]
Haha yeah my calculations are odd. They where experimental... 
I started with the exact same code for `mask`, which would be logical. But I think I just messed up my mask settings in blender. Sorry about that. :innocent:

> "group": sum([2**i for i, v in enumerate(obj.game.collision_group) if v])

Nice, looks really smooth.

I removed the `GameObject` code and will make a new PR if I can make that change work.

**Comment by Nananas** [comment]
It seems doing the following works:
```
// Inside a GameObject
scene.world.removeRigidBody(this.body);
scene.world.addRigidBody(this.body,newCollGroup ,newCollMask);
```

But this works too:
```
// Inside a GameObject
this.body.getBroadphaseProxy().collisionFilterGroup = newCollGroup;
this.body.getBroadphaseProxy().collisionFilterMask= newCollMask;
```

Which would be prefered/correct?

**Comment by GoranM** [comment]
Instead of additional commits, you should have used the --amend option to change the existing commit.

You need to squish this into one commit.

**Comment by Nananas** [comment]
Alright, thanks. I learned something nice today :+1:.

**Pull request merged**
