### PR TITLE
(#300) Bug: scale() now activates body

### PR DESCRIPTION
**Pull request by rafcolson**

### CODE REVIEW

**Comment by GoranM** [comment]
Couldn't you simply simply add `body.activate(true)` to the beginning of the scale method?

**Comment by rafcolson** [comment]
>Couldn't you simply simply add ```body.activate(true)``` to the beginning of the scale method?

Yes. But there's no need to activate the body if it's a child, right? And the method already checks if it's a child so better take advantage of that. The same goes for the ```transform``` method. 

But if you want me to just add ```body.activate(true)```, I don't mind changing it. I don't think redundant activation would cause any problems.

**Comment by GoranM** [comment]
I'm not exactly sure on the complete bullet requirements, but I've experienced bugs when moving static objects without activating them first.

So, I think it's best to just add `body.activate(true)`.

**Comment by rafcolson** [comment]
Okay. Done.

**Pull request merged**
