### PR TITLE
(#275) add, set, remove scene by name and return scene

### PR DESCRIPTION
**Pull request by rafcolson**

### CODE REVIEW

**Comment by GoranM** [comment]
Shouldn't set create a new scene, and place that into given position?

**Comment by rafcolson** [comment]
@GoranM Yes, but it already does. Let's say you want to replace the HUD with a Menu, then you would do this, for example:
```Java
Bdx.scenes.set(1, new Scene("Menu"));
```
You created a new scene, named "Menu", and added it to the list at the given position.

The built-in method ```set(int index, E element)``` (with E being Scene in this case) is exactly doing the latter. It **"Replaces the element at the specified position in this list with the specified element."**

So I think ```ArrayListScenes.set(int index, Scene scene)``` could be omitted. If you think so too, I can remove the code in this commit.

**Comment by GoranM** [comment]
Unlike ArrayListScenes.set, the built-in set method doesn't actually call add, so it's not going to initialize the scene as we require. 

Anyway, my question relates to the set method that you added (`set(int, String)`), not the one that was already there.

**Comment by rafcolson** [comment]
Sorry, I totally missed those things. Thanks. PR updated.

**Comment by rafcolson** [comment]
@GoranM Maybe better to first merge this one so I can rebase ```replaceModel()```.

**Comment by GoranM** [comment]
The commits don't depend on each other, so there's no need to rebase.

**Pull request merged**
