### PR TITLE
Bug #68: Set compileSdkVersion for android.

### PR DESCRIPTION
**Pull request by rafcolson**

### CODE REVIEW

**Comment by GoranM** [comment]
There's two commits, and they both have the same message ...

Which commands did you actually run?

The last PR was fine - it's good practice to work in a new branch. You just needed to --amend the existing commit, and then do a force push to the compileSdkVersion branch. I'm not really sure why you couldn't do that.

> I pulled a request from a branch and I don't know how to clone that to my GitHub.

You're not supposed to pull any requests - You make pull requests, and then it's up to me to pull them in.

**Comment by rafcolson** [comment]
>There's two commits, and they both have the same message ...

It's nerve wrecking.

>it's good practice to work in a new branch.

I don't know what you mean exactly, but I guess you mean that whenever I want to change code, I mustn't commit to my Master, but to a separate branch.

>You just needed to --amend the existing commit, and then do a force push to the compileSdkVersion branch. I'm not really sure why you couldn't do that.

I assume that In order to force push the existing commit with Git Shell I have to clone it to the GitHub on my computer. I have to try that out again, because previously I couldn't find it in the lists of commits of my cloned bdx folder, so I assumed I had to commit that first to my Master. But if I'm understanding correctly what you are saying I shouldn't, but just run those two lines you gave me.

>You're not supposed to pull any requests - You make pull requests, and then it's up to me to pull them in.

So now you understand why I pulled a request to my own Master. It was just so the commit of my separate branch would be editable, I thought.

Anyway, before I pull any requests to your Master, I'll do some exercises with the Git Shell and GitHub. I don't want to be dealing with this kind of stuff the next time.

**Comment by GoranM** [comment]
> I don't know what you mean exactly, but I guess you mean that whenever I want to change code, I mustn't commit to my Master, but to a separate branch.

It's best to maintain master as an up-to-date reflection of the upstream repo (GoranM/bdx), and then do work in feature branches, which can be used to make pull requests.

When your feature is merged, you can simply delete that branch, and update your master from the upstream source, which would then include commits from your recently merged branch.

>  But if I'm understanding correctly what you are saying I shouldn't, but just run those two lines you gave me.

Essentially, yes. But right now, looking at the state of your github fork, I think you can just do the following (assuming that your local compileSdkVersion branch is exactly the same as the one currently in your fork):

```
git checkout compileSdkVersion
```

Then open createproj.py, and change get_version to get_version_dir_name. Save file. Then do this:

```
git commit --amend -am "Bug #68: Set compileSdkVersion for android."
git push -f origin compileSdkVersion
```

Your last pull request (#79) should now have a single commit, with the proper changes, and if it does, you should close this one, and reopen 79.

> So now you understand why I pulled a request to my own Master. It was just so the commit of my separate branch would be editable, I thought.

A "pull request" is what you make on github (this thread, for example) - It's not a git operation, so I still don't understand what you mean when you say "I pulled a request to my own Master".

> I'm pretty much incompetent at this point.

I think you're doing fine. Git is not easy (in my opinion).

**Comment by rafcolson** [comment]
Done.

**Pull request closed without merging**
