### PR TITLE
(#199) - Random.random() with arguments.

### PR DESCRIPTION
**Pull request by SolarLune**
Additional random() function with ability to provide minimum and maximum values.

### CODE REVIEW

**Comment by GoranM** [comment]
Why not mini - maxi, and not min - max? Is there some significance to the trailing 'i'?

**Comment by SolarLune** [comment]
Fixed. Also, the random vector improvements are in this commit because they depend on random.random.

**Comment by GoranM** [comment]
That doesn't seem like the right code - It touches Bullet.java.

**Comment by SolarLune** [comment]
Huh, I thought I didn't commit that. Fixed, thanks.

**Comment by GoranM** [comment]
Seems like something went wrong again: Random.vector(min, max) is missing, and you have a Random.direction(min, max), which is not supposed to be there.

**Comment by SolarLune** [comment]
Huh? You told me to change direction() instead of vector() in issue #198.

**Comment by GoranM** [comment]
I said:

> You should change Random.direction, so that it can only return vectors of non-zero length.

I didn't tell you to overload the method with min/max arguments.

**Comment by SolarLune** [comment]
I guess I misunderstood you. Fixed.

**Pull request merged**
