### PR TITLE
Bug #100: Props support for group instance

### PR DESCRIPTION
**Pull request by rafcolson**
Note: Only properties sharing the same name will be overwritten.

### CODE REVIEW

**Comment by rafcolson** [comment]
Let me know if there's a way to do this without converting to HashMap.

**Comment by GoranM** [comment]
I don't know if this can all be done with JsonValue, instead of converting to HashMap (I kinda assumed that you would research that), but I guess a HashMap is fine.

You can cut a bit of code in your initialization process:

```java
g.props = new HashMap<String, JsonValue>();

for (JsonValue prop : gobj.get("properties")){
    props.put(prop.name, prop);
}
```

JsonValue supports Java iteration conventions, so that should work fine.

However, looking at this line:

```java
g.props.putAll(inst.props);
```

In this context, `g.props` references the original HashMap that was created for the template object, as you can see [here](https://github.com/GoranM/bdx/blob/master/src/com/nilunder/bdx/Scene.java#L284), so wouldn't that make props for all instances exactly the same?

**Comment by rafcolson** [comment]
>I don't know if this can all be done with JsonValue, instead of converting to HashMap (I kinda assumed that you would research that), but I guess a HashMap is fine.

Unfortunately my research doesn't give the best results always, especially with Java, because I'm just learning it. Another reason definitely is that I'm searching for answers in the API's's and Stackoverflow. It's just not enough.

>JsonValue supports Java iteration conventions, so that should work fine.

See! I didn't know that.

>However, looking at this line:
```java
g.props.putAll(inst.props);
```
In this context, `g.props` references the original HashMap that was created for the template object, as you can see [here](https://github.com/GoranM/bdx/blob/master/src/com/nilunder/bdx/Scene.java#L284), so wouldn't that make props for all instances exactly the same?

Essentially, yes. An added instance (e.g. ```cube_inst = scene.add("Cube")```) will inherit all properties of the template. A group instance will too, but will preserve all properties that may be added to it.

How do you think it should be then, if I may ask?

**Comment by rafcolson** [comment]
I don't understand why those merges pop up here, it's a bit frustrating. I'm closing this and reopening a new PR to avoid confusing.

**Pull request closed without merging**
