### PR TITLE
(#320) GameObject.dimensions() now from Blender dimensions

### PR DESCRIPTION
**Pull request by rafcolson**
Note: I thought it would be best to keep the old method for Text objects exclusively.

### CODE REVIEW

**Comment by GoranM** [comment]
> I thought it would be best to keep the old method for Text objects exclusively.

Why?

**Comment by rafcolson** [comment]
Sorry, I guess I should just update ```aabb``` and ```dimensionsNoScale``` in ```Text.set()```. Then there's no need for an override. Working on it.

**Comment by rafcolson** [comment]
PR updated. I'll leave the update of ```dimensionsNoScale``` in ```Text.set()``` for another time as I still have to figure out how to calculate it. Also, the dimensions in Blender are not exactly the same as those in BDX, which I figure is due to the font conversion. So I'm not sure how to tackle this. Should I maybe set ```dimensionsNoScale``` right after conversion at initialization?

Anyway I guess you could just merge this, if no one cares about this update right now.

**Comment by GoranM** [comment]
Dimensions for Text object will have to incorporate character width/height - It's something that should be done in a different PR.

**Pull request merged**
