### PR TITLE
Extra mouse & cursor functions

### PR DESCRIPTION
**Pull request by Nananas**
I added some extra mouse and cursor functions.

I'm not pretty sure about the naming of `cursorLock` though.

### CODE REVIEW

**Comment by GoranM** [comment]
Why Vector2d instead of Vector2f?

**Comment by Nananas** [comment]
Woops, mistake. Fixed.

**Comment by GoranM** [comment]
position() is trying to return a Vector2d ...

Please make sure to actually test your build after you make changes.

**Comment by Nananas** [comment]
Right :see_no_evil:

**Pull request merged**
