### PR TITLE
Fix for issues #379 and #380

### PR DESCRIPTION
**Pull request by billy1380**

### CODE REVIEW

**Comment by GoranM** [comment]
The first commit should be split into two: You should have one for adding eclipse files to gitignore, and another for removing the use of String.format.

If your formatForDisplay method works (@rafcolson can probably help you test that) , I'll accept your code, because it resolves a bug, but it should be considered a temporary fix, because, ideally, we would be able to make a proper alternative for String.format, which would just work when compiling with GWT.

It should be possible to do that via "super source", as documented [here](http://www.gwtproject.org/doc/latest/DevGuideOrganizingProjects.html#DevGuideModuleXml) (under the heading: "Overriding one package implementation with another").

**Comment by billy1380** [comment]
@GoranM don't worry about accepting the code with the current commits... I can easily recreate the commits by creating another branch and applying the changes one at a time. I just wanted some feedback. Give me a nod if you prefer that.

I have built the code and run it since the last post but the project crashes after loading resources as can be seen [http://spacehopperstudios.com/testenv/testgame/](http://spacehopperstudios.com/testenv/testgame/ "BDX Test Game"). I know it loads some resources successfully because I can see them come down in the dev tools.

In superdev mode the message is "Cannot read property type_0 of undefined" but I would rather someone else had a go with before I raised a bug especially that I think that it might be a libgdx issue.

About String.format - I think String.format ultimately wraps java.util.Formatter and the implementation of the format method is a grizzly thing (because of the versatility mixed with locale awareness). Been looking for some code with a compatible license that I might be able to base it on... but found nothing so far (except some suggestions on the gwt issue I linked to). One thing that might be useful is if we can find code from the apache harmony project we might be able to use that: thoughts?

Anyway... let me know how the testing goes and I can sort the commits however you prefer.

**Comment by billy1380** [comment]
I setup an html5 project from scratch with gdx-setup.jar and built it for testing using superdev and it runs fine, so it might be a bdx/my code changes after all :sob:

**Comment by rafcolson** [comment]
So do I have to test your commit?

**Comment by billy1380** [comment]
If you get a chance, please do.

**Comment by rafcolson** [comment]
I've tested the commits. Everything seems to work fine.

**Comment by billy1380** [comment]
Nice one... Thanks very much. I will close this and submit another pull request for the String.format changes only.

**Comment by billy1380** [comment]
@GoranM new pull requests submitted.

**Pull request closed without merging**
