### PR TITLE
(#581) Custom Material Shaders fix.

### PR DESCRIPTION
**Pull request by SolarLune**
Adding MaterialShader and renaming ShaderProgram to ScreenShader.
Calling ArrayListMaterials.unique() will rename cloned materials to try to keep them unique.

### CODE REVIEW

**Comment by GoranM** [comment]
> Calling ArrayListMaterials.unique() will rename cloned materials to try to keep them unique.

Aren't they already unique, even if they have the same name? I'm not really sure if this is necessary.

**Comment by SolarLune** [comment]
They are unique, yeah, it's just that the material shader system is dependent on the material's name, so if two materials share a name that's in the matShaders HashMap, they'll both get the shader applied to them. By automatically incrementing a value in the name, this is avoided to some extent. 

Do you think it would be better not to have it?

**Comment by GoranM** [comment]
Shouldn't the clones of a given material use the same shader? If that's the case, then they should have the same name.

If there's a circumstance in which a cloned material needs to use a different shader, I suppose that we could have a shader reference on the material itself - That seems like it would make more sense, given that we have our own material class.

**Comment by SolarLune** [comment]
Yeah, I guess that does make sense. I'll leave the unique() function alone and approach the shader to material setup another time, then.

PR updated.

**Comment by SolarLune** [comment]
PR fixed, as it was touching ArrayListMaterials.unique(), which is supposed to be taken out, and so would've caused a conflict. I think it should be good to go at this point.

**Pull request merged**
