### PR TITLE
(#929) Always ignore data block name of font

### PR DESCRIPTION
**Pull request by rafcolson**

### CODE REVIEW

**Comment by SolarLune** [comment]
Hey, I think you're assuming the `fntx` file is in the same location as the source `ttf` file - this isn't always the case. For me, at least, I store my fonts external to my project folder (since multiple projects could use them).

**Comment by SolarLune** [comment]
Had a previous post, but that was incorrect. I'm running into an issue with BDX being unable to read the `fntx` file for a font that I'm using a blend file:

```python
RuntimeError: Error: Traceback (most recent call last):
  File "/home/solarlune/.config/blender/2.78/scripts/addons/bdx/exporter.py", line 908, in execute
    return export(context, self.filepath, self.scene_name, self.exprun, self.apply_modifier)
  File "/home/solarlune/.config/blender/2.78/scripts/addons/bdx/exporter.py", line 857, in export
    bdx["models"].update(srl_models_text(ts, fonts_dir))
  File "/home/solarlune/.config/blender/2.78/scripts/addons/bdx/exporter.py", line 261, in srl_models_text
    for t in texts}
  File "/home/solarlune/.config/blender/2.78/scripts/addons/bdx/exporter.py", line 261, in <dictcomp>
    for t in texts}
  File "/home/solarlune/.config/blender/2.78/scripts/addons/bdx/exporter.py", line 249, in fntx
    with open(j(fntx_dir, font_name(t.font) + ".fntx"), 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/solarlune/Documents/Projects/BDX/NewTest/android/assets/bdx/fonts/please1.fntx'

```

I believe the issue is that FontWriter is being passed the font's name as the output file name, I think, here: https://github.com/GoranM/bdx/blob/master/blender/bdx/exporter.py#L765

The commands being passed includes the font's name, when you want it to be the font's filename, right?

**Comment by rafcolson** [comment]
> The commands being passed includes the font's name, when you want it to be the font's filename, right?

I don't understand completely why it has been working on my end without this change, but of course it only makes sense if also the FontWriter uses the file name. Hopefully this will cut it for you. And thanks.

**Comment by rafcolson** [comment]
Putting this on hold for just a few minutes.

**Comment by GoranM** [comment]
Waiting for @SolarLune to confirm.

**Comment by SolarLune** [comment]
I don't see any issues with this, on testing, so it should be good to go.

**Pull request merged**
