### PR TITLE
(#537) Popup error when vertex number exceeds 32767

### PR DESCRIPTION
**Pull request by Fr0sk**

### CODE REVIEW

**Comment by GoranM** [comment]
Shouldn't this code be in the engine, rather than the exporter? The limitation is on the libgdx side - it's not a blender problem.

@SolarLune - Comments on the commit don't seem to be counted as comments in the PR, even though they're shown here. I would suggests restricting your comments to the PR, to ensure that all relevant parties receive a notification.

**Comment by SolarLune** [comment]
Oh, I didn't know. OK, I'll keep that in mind. Thanks!

**Comment by Fr0sk** [comment]
Sorry, today I'm on a birthday and don't have the time to review the commit to change it. As @SolarLune, I also think this error should be thrown in Blender, as it happens when someone change a mesh in a way that exceeds the 32767 vertices. Since a mesh change to be applied has to be exported through blender, I think that preventing exporting to finish when that happens is better. 

> Basically, we're already looping through each object elsewhere - there's no need to do it again in execute().

I coded this check here because I think all the checks should be made before any of real work begin. That's just the way I code, but this project isn't mine, of course I will do it the way you guys decide :) 

But to be clear when I pick this up tomorrow, the check stays on the blender side? Should I put it on another object loop?

**Comment by GoranM** [comment]
It seems more elegant to simply catch the OutOfMemoryError where it actually happens, and throw our own custom error instead, but if you want to do it in the exporter, that's fine too.

**Comment by rafcolson** [comment]
>It seems more elegant to simply catch the OutOfMemoryError where it actually happens

I would agree. This is consistent with any error messages during runtime. @Fr0sk It's up to you, but here's the commit if you think it's fine either way.

**Comment by SolarLune** [comment]
Yo @Fr0sk, you still there about this?

**Comment by Fr0sk** [comment]
Hey @SolarLune. It seems that I got caught up with my university work and have little to no time to get into this side projects, so my apologies. I think @GoranM and @rafcolson are probably right, so it might be better to throw it where it really happens. If anyone wants to pick it up, feel free ;)

**Comment by rafcolson** [comment]
Thanks @Fr0sk. PR submitted.

**Comment by rafcolson** [comment]
@GoranM Could we close this? @Fr0sk probably isn't around to do so..

**Comment by GoranM** [comment]
Ok.

**Pull request closed without merging**
