### PR TITLE
(#718) framerateProfile only in main scene & don't end profiler scene & remove warning

### PR DESCRIPTION
**Pull request by rafcolson**

### CODE REVIEW

**Comment by GoranM** [comment]
@SolarLune

Does this resolve the issue?

**Comment by rafcolson** [comment]
I'm currently resolving conflicts with master, so...

**Comment by rafcolson** [comment]
PR updated and tested.

**Comment by SolarLune** [comment]
OK, I just tested this. 

It doesn't work the way that I personally think it should; I feel like it should check just the current, "main" scene for the profiler being active, and go with that, rather than loop through all scenes to see if any of them have the profiler enabled.

**Comment by SolarLune** [comment]
I guess an alternative would be to alter Blender's actual behavior by having the Game menu settings (i.e. physics visualization and framerate and profiler) apply across all scenes whenever they're ticked or unticked. Personally, I think I'd prefer that, since it'd solve the problem at its base with turning on a debug setting, going to another scene, and finding it off.

**Comment by rafcolson** [comment]
>It doesn't work the way that I personally think it should; I feel like it should check just the current, "main" scene for the profiler being active, and go with that, rather than loop through all scenes to see if any of them have the profiler enabled.

Okay, I'll change this.

>I guess an alternative would be to alter Blender's actual behavior by having the Game menu settings (i.e. physics visualization and framerate and profiler) apply across all scenes whenever they're ticked or unticked. Personally, I think I'd prefer that, since it'd solve the problem at its base with turning on a debug setting, going to another scene, and finding it off.

That would be a suggestion for a new issue. Feel free to make it at any time. For now, I'll be concentrating on fixing the issue at hand.

**Comment by rafcolson** [comment]
PR updated. @SolarLune Like before, the profiler will only be enabled when it's enabled in the main scene. Give a sign to @GoranM when you think this is good to go.

**Comment by rafcolson** [comment]
Problem fixed.

**Comment by SolarLune** [comment]
OK, I think this is correct, but if you use `put()` and the Profiler's not visible, it'll print "Warning: "Show Framerate and Profile" is not enabled in the main scene" to the console.

Could I ask, why have the Profiler print that?

**Comment by rafcolson** [comment]
It doesn't make sense to add properties if the profiler is not visible. The warning should make the user aware of this.

**Comment by SolarLune** [comment]
I don't really see the point; if the profiler's invisible, then the user won't see the properties they put to the profiler. I don't think the user needs a message to be reminded of this - it's a basic concept of profiling their game. Also, this means that the console's cluttered with the message any time the developer's debugging by using Profiler.props.put. They basically have to remove the `put()` calls if they want to print out any other information.

Perhaps it would be best to remove it.

**Comment by rafcolson** [comment]
>They basically have to remove the put() calls if they want to print out any other information.

Not quite. There is no sense in adding properties if the profiler isn't visible. I'm sure you agree with that. And so, logically, you would first check if the profiler is visible before doing anything else with it.
```java
if (Bdx.profiler.visible()){
	Bdx.profiler.props.put("myProp", "myValue");
}
```
The warning is just a reminder not to alter the scale or the visibility of the tick rate, subsystems, gl, props or add props when the profiler is visible.

That said, I don't mind removing it. Instead I'll put a warning in the API for the Profiler.

**Comment by SolarLune** [comment]
> There is no sense in adding properties if the profiler isn't visible. I'm sure you agree with that. 

I mean yeah, I agree, but it's not an intentional thing. While you're debugging, you might put a value to the props HashMap, enable the Profiler to check the value, run the game, then later disable the Profiler. It's not like you intentionally are trying to put stuff to the Profiler while it's invisible.

> The warning is just a reminder not to alter the scale or the visibility of the tick rate, subsystems, gl, props or add props when the profiler is visible.

What happens if the profiler's invisible when making these changes? Is it that the Profiler doesn't apply the changes?

**Comment by rafcolson** [comment]
>What happens if the profiler's invisible when making these changes? Is it that the Profiler doesn't apply the changes?

I only made sure there wouldn't be exceptions, so some things may be applied, but other things may. Like props can be added and removed, but changing the visibility of the props will not be possible.

**Comment by SolarLune** [comment]
Hmm, I see. That makes sense.

**Comment by rafcolson** [comment]
>Hmm, I see. That makes sense.

So, if you think this is ready, just give a hit, okay? And thanks for the review.

**Comment by SolarLune** [comment]
OK, I tested it, and it seems like it works fine. Thanks!

**Pull request merged**
