### PR TITLE
(#234) - Objects in group inherit instance's scale.

### PR DESCRIPTION
**Pull request by SolarLune**

### CODE REVIEW

**Comment by GoranM** [comment]
It doesn't work when the root object has more than one child.

Also, I don't really see the rationale for this:

```java
for (GameObject c : g.children) {
	Vector3f offset = c.position().minus(g.position());
	c.position(g.position());
	c.move(offset);
}
```

Mathematically, it should not change c.position: 

```java
c = 2
g = 1
offset = c - g   // 2 - 1 = 1
c = g  // c = 1
c = c + offset  // c = 1 + 1 = 2
```

If you print c.position(), before and after, you'll see that it stays the same.

I suspect the visible changes are due to how the transform chain is updated, and how scale is incorporated in that process ... It's possible that there's bug in GameObject.scale, relating to how it affects children, even for non-instanced objects.

**Comment by SolarLune** [comment]
Ah, you're right. 

Hm, there doesn't seem to be any scaling issues when not dealing with groups. It seems like it might be the process of spawning in the objects after the parent and then re-parenting them that houses the problem? I'm unsure, though.

**Comment by GoranM** [comment]
You should be able to see the problem when actually setting a new scale, in game, for a given parent.

I've made a commit that should fix that - test it out.

**Comment by SolarLune** [comment]
OK, I think I saw some weird behavior using the scale() function in-game that's not there now. Thanks for the fix - simply applying the scale seems to work now. PR should be updated.

**Pull request merged**
