### PR TITLE
Profiler test (#76)

### PR DESCRIPTION
**Pull request by rafcolson**
This is a simple profiler. It evaluates three processes in BdxApp, but to be honest, to me it doesn't say much. "scenes" takes all the time in comparison with "graphics" and "input". But it's a concept. Let me know what you think about it.

Edit:

You can get the profiler percentages (HashMap\<String, Float\>) like so:
```
System.out.println(Bdx.profiler.pcts());
```

### CODE REVIEW

**Comment by SolarLune** [comment]
Cool. You would probably do well to split up the "scenes" section into several pieces, as that's logic execution, rendering, and transformation application.

**Comment by rafcolson** [comment]
Yes, that's more practical. Updated.

**Comment by SolarLune** [comment]
^ That could work well. I don't think there's any built-in method to draw text and bars apart from doing it in pure OpenGL, I suppose, so a profiler .bdx file could be packaged with BDX and, of course, be placed in the scenes folder. Consisting of text and bars. If you have a certain profiler variable on, then it would add in that scene (and, I suppose, not put it in with the scenes list to keep you from accidentally removing it during gameplay).

The actual updating of the profiler info could be done with a single source file that handles the scaling of those bars and text output on those text objects to represent the profiler data. It might be possible to hide that file by naming it with a "." at the beginning, too.

The alternative would be to do it in OpenGL, I guess; not too sure how difficult and how much extra code that would be to implement.

**Comment by rafcolson** [comment]
With the overlay scene approach the Profiler scene should always be on top too.

**Comment by GoranM** [comment]
Instead of calling static methods directly on the class, you should just create an instance of the Profiler on `Bdx.profiler`. It would be more consistent with other, globally available objects.

The "process" / "subProcess" semantics are confusing, because they already reference existing programming concepts (on first look, some programmers may think you're talking about code that runs in a different address space). Just use `startTime` and `stopTime` and simple/short names like that; for overall profiler times, use profStartTime and profStopTime. I think that would be less confusing, and less visual clutter.

Having to include all the code from one time call to another is a pretty big limitation; That should be redesigned into something a little more flexible, so we can do this:

```java
Profiler p = Bdx.profiler;

p.start("something");
// code
long millis = p.stop("something");
System.out.println(millis); // if I just want time for one run, instead of add on loop

// code I want to skip

p.start("blah");
// blah code
p.stop("blah");
// after blah
p.stop("after");
// more
p.stop("more");
```

**Comment by rafcolson** [comment]
I 'll redesign it.

**Comment by rafcolson** [comment]
It finally works, so you can have a look. In the meantime I'll start with constructing the Profiler overlay scene.

Is ```Bdx.profiler.pcts()``` (percentages) descriptive enough?

**Comment by SolarLune** [comment]
`Bdx.profiler.percents()` or `Bdx.profiler.percentages()` would probably be fine; `pcts()` doesn't really sound like "Percentages" or "percents" to me. Looking great, Raco!

**Comment by rafcolson** [comment]
Had to start all over because my master's remote's were all messed up.

**Pull request closed without merging**
