### PR TITLE
GameObject.ghost() (#118)

### PR DESCRIPTION
**Pull request by rafcolson**

### CODE REVIEW

**Comment by SolarLune** [comment]
Aww yissss

On a side-note, it's crazy to see how easy it is to expose features that Bullet supports but that the BGE doesn't (for whatever reason). It's fun to see others work on these kinds of features as well as work on them oneself.

Nice work, Raco.

**Comment by rafcolson** [comment]
Thanks. Yes, there's a lot of potential in this. If I'm not mistaken, it's even possible to "change" objects from Dynamic to Static or No Collision.

Ah yes, I almost forgot to mention that I deliberately got "SENSOR" out of the picture in exporter.py because it is treated as a Static Ghost anyway. I removed an 'if' in method Bullet.setCollisionFlags().

Also, with objects that have No Collision it should be noted that ghost will be ```true```. Does it seem necessary to change this to ```null```?

**Comment by GoranM** [comment]
> Yes, there's a lot of potential in this. If I'm not mistaken, it's even possible to "change" objects from Dynamic to Static or No Collision

Instead of ghost methods, it might be better to have bodyType methods - that would also remove the need for a ghost argument in Bullet.setCollisionFlags.

> I deliberately got "SENSOR" out of the picture in exporter.py because it is treated as a Static Ghost anyway. I removed an 'if' in method Bullet.setCollisionFlags().

The exporter should not "compress" options available in Blender, especially when there is no significant benefit in doing so; For now, we set the same collision flags for both sensor and ghost, but that may change.

In general, exporter output should aim to reflect data that's available; Which of that data we use, and how, is something to be codified in the engine.

**Comment by rafcolson** [comment]
>Instead of ghost methods, it might be better to have bodyType methods - that would also remove the need for a ghost argument in Bullet.setCollisionFlags.

I'm not exactly sure what you mean by that. You mean to change bodyType to: "STATIC_GHOST", "DYNAMIC_GHOST" and "RIGID_BODY_GHOST" when ghost is enabled?

>For now, we set the same collision flags for both sensor and ghost, but that may change.

Yes, I thought this might be the case. So I'm changing it.

**Comment by GoranM** [comment]
I mean, instead of a `GameObject.ghost(boolean ghost)` method, you can have a `GameObject.bodyType(String type)` method, which would basically just call `Bullet.setCollisionFlags(body, type)`.

**Comment by rafcolson** [comment]
Yes, I just tried that. The problem is that it's a bit inconsistent unless we add the ability to change body types too. But you would choose not to add such an ability then using a method such as ```GameObject.bodyType(String type)``` for enabling/disabling ghost would be a bit messy.

What I mean is that users could think they can change the body type when it's not supported.

**Comment by GoranM** [comment]
Oh, wait, "GHOST" is not a body type ... right, so it would probably be best to have ghost methods.

However, I don't think we would need any additional fields, because whether or not an object is  "GHOST" can be determined via `GameObject.body.getCollisionFlags()`, and setting an object to ghost can be done via GameObject.body.setCollisionFlags`.

**Comment by rafcolson** [comment]
What do you mean by 'additional fields'? No ```GameObject.ghost()``` method you mean?

**Comment by GoranM** [comment]
By fields, I mean variables.

You don't need a ghost boolean on a GameObject, and you don't need a bodyType string either (which also means that you don't need to write code to set them).

You can just have ghost methods like this:

```java
public boolean ghost(){
    return body.getCollisionFlags() & CollisionFlags.NO_CONTACT_RESPONSE;
}

public void ghost(boolean ghost){
    int flags = body.getCollisionFlags();
    int noContact = CollisionFlags.NO_CONTACT_RESPONSE;

    if (ghost)
        flags |= noContact;
    else
        flags &= ~noContact;

    body.setCollisionFlags(flags);
}
```

I think that will set the flags properly (assuming I used the right bitwise operation to add or remove the no contact flag from existing flags).

**Comment by rafcolson** [comment]
Much, much better that way. Thanks. (I seem a bit useless, but hey, I'm learning a lot).

**Pull request closed without merging**
