### PR TITLE
modelInstance for all objects

### PR DESCRIPTION
**Pull request by rafcolson**

### CODE REVIEW

**Comment by rafcolson** [comment]
Forgot to put the Issue in the title, sorry.

#66

**Comment by GoranM** [comment]
You should be able to use --amend to change the commit, along with the commit message (as I explained in the past).

The commit itself looks ok, but you would also need to search the codebase for
`modelInstance != null` and `modelInstance == null`, because now those conditionals are probably redundant, and should therefore be removed as a part of this PR.

PS: Don't recreate the branch, as I suspect you did for the last PR. Simply do the following:

```
git checkout modelInstance
```

Edit code, save files, then:

```
git commit --amend -am "modelInstance for all objects (#66)"
git push -f origin modelInstance
```

That should change this PR, so there should be no need to create a new one.

**Comment by rafcolson** [comment]
It should be okay now.

**Comment by GoranM** [comment]
Did you search the entire code-base for those patterns?

There's still a redundant check in GameObject.scale

**Comment by rafcolson** [comment]
Sloppy of me. Done.

**Pull request merged**
