### PR TITLE
Collision group & mask update

### PR DESCRIPTION
**Pull request by Nananas**
##### Continued from #144 : 

Allows change to the collision group and mask. (Also added getters and setters).

Added a `updateCollisionFilter()` function that removes and adds the `RigidBody` to the world. This can be extended with a `dirty` flag, only removing/adding the `RigidBody` when the group & mask have been changed...

(This is based of the `master` branch. I don't really know if this is very smart.

### CODE REVIEW

**Comment by GoranM** [comment]
`updateCollisionFilter()` seems unnecessary, and the same can be said for storing the value of group/mask on the game object: You can just re-add the body in the setters, and the getters can simply return the value of `body.getBroadphaseProxy().collisionFilterGroup/Mask`.

**Comment by Nananas** [comment]
Updated.

Note: This will throw a nullpointerException if the rigidbody has not been added to the scene. Do you think a check is necessary? Or will it make debugging harder?

**Comment by GoranM** [comment]
No need for that first commit, because it contains changes that have already been merged in from the last PR.

The second commit should be rebased on top of existing code in master.

Don't worry about checks for now.

**Comment by Nananas** [comment]
Uh ok. I thought github handled the rebase on its own.
Is this better?

**Pull request merged**
