### PR TITLE
(#524) Material change functions.

### PR DESCRIPTION
**Pull request by SolarLune**

### CODE REVIEW

**Comment by GoranM** [comment]
I don't think you have to do anything with m_ps. With m_verts ordered, it should be possible to change:

```python
for m, tris in m_tris.items():
```

to

```python
for mat in mesh.materials:
    m, tris = mat.name, m_tris[mat.name];
```

And that should just work.

**Comment by SolarLune** [comment]
I just tried this, but it doesn't work if a material is used that vertices aren't using.

**Comment by GoranM** [comment]
You mean there is a mat.name which doesn't exist as a key in m_tris, and you get a key error?

You can just skip over those - If they don't map to any vertices, they are not actually used, so it shouldn't be a problem.

**Comment by SolarLune** [comment]
> You mean there is a mat.name which doesn't exist as a key in m_tris, and you get a key error?

Yeah, thanks.

Your proposed solution didn't work for meshes that have no materials, so I added that into srl_models, as well.

PR updated.

**Comment by GoranM** [comment]
Do you want me to make a new release now?

**Comment by SolarLune** [comment]
Yeah, sure. Thanks for the merge.

**Pull request merged**
