### PR TITLE
removed spaces from parameters and fixed float formatting

### PR DESCRIPTION
**Pull request by billy1380**

### CODE REVIEW

**Comment by rafcolson** [comment]
It's still the same as before, which is not surprising because it's virtually the same commit as before.

The text is too long because of the redundant spaces. And that's why "fps" is not completely shown ("fp"). That's why the bars start inside the text.

**Comment by billy1380** [comment]
Apparently in String.format the 4 in 4.1 is the width of the entire field. This means that the issues can either be fixed by calling the current method `addFloat` with 2, 1 or changing the meaning of the 3rd parameter to field padding instead of integer part padding. I have opted for the 2nd solution just in case these functions are later recycled into a String.format implementation.

**Comment by GoranM** [comment]
I'm not sure what this PR is supposed to fix - Didn't @rafcolson already fix the formatting issues with your patch?

**Comment by billy1380** [comment]
It removes the spaces from the parameters and puts them into the formatting method which now behaves like String.format did

**Comment by rafcolson** [comment]
>It removes the spaces from the parameters and puts them into the formatting method which now behaves like String.format did

It doesn't, at least on my end. As I already explained:

>The text is too long because of the redundant spaces. And that's why "fps" is not completely shown ("fp"). That's why the bars start inside the text.

@billy1380 Could you please confirm if this is also true on your end, or not. If not, then maybe we should look first why we have different results. If so, then this commit should be adjusted so it does not change anything to the profiler visually.

**Comment by billy1380** [comment]
I have adjusted the commit since and the fps now appears and the bars are no longer overlapped.

**Comment by rafcolson** [comment]
Now it's good. You could always merge both commits to one by doing ```git reset HEAD^``` and then doing ```git commit --amend -am removed spaces from parameters and fixed float formatting```.

**Comment by GoranM** [comment]
Please follow rafs advice, and make this into a single commit.

**Comment by billy1380** [comment]
I am not sure what that has achieved; anyway... I ran the command and pushed the changes. It now looks like a mess to me.

If you are really hell-bent on getting a single commit for the changes I can re-do the changes on a clean branch.

Let me know.

**Comment by billy1380** [comment]
Actually... I will just do that anyway... closing.

**Pull request closed without merging**
