### PR TITLE
Added valid boolean to GameObjects to check if they're valid.

### PR DESCRIPTION
**Pull request by SolarLune**
GameObjects now have a private field named `valid`, which gets set to true on creation and set to false on end()-ing.
Added valid() function check to check if a GameObject is valid / present in the game world.
Added parent checks to end() functions to remove GameObjects from parents' children lists if they're removed.

### CODE REVIEW

**Comment by GoranM** [comment]
Instead of having the same code in `end` and `endNoChildren`, I think it would be better to just put it into scene.remove.

Also, note that calling `obj.parent(null)` will properly "unparent" the object in question ([as stated in the API reference](https://github.com/GoranM/bdx/wiki/API-GameObject#parent-p)), so there's no need to manipulate the parent's children list directly.

**Comment by SolarLune** [comment]
Putting it into scene.remove sounds OK, but valid is currently a private field of GameObject, so it'd have to either be public (and so there wouldn't really be a need to have a valid() function), or there'd have to be a valid() setter (which doesn't make sense as it's not something that should be used by other objects or even the GameObject directly).

OK, obj.parent(null) can be used.

**Comment by GoranM** [comment]
In the API reference, we point out that "Unless otherwise labeled, all fields should be considered read-only", so you can just make `valid` a public field, and developers can use that directly.

**Comment by SolarLune** [comment]
PR Updated.

**Pull request merged**
