### PR TITLE
(#444) - Down-sampling for 2D Filters.

### PR DESCRIPTION
**Pull request by SolarLune**

### CODE REVIEW

**Comment by GoranM** [comment]
`renderSize` implies a set size, not a scaling factor. I think `renderScale` would be a more appropriate name.

--

Instead of having an `overlayBuffer`, couldn't you simply leave `frameBuffer` uncleared?:

```java
if (!filter.overlay)
    frameBuffer.clear()
```

That would just draw the `tempBuffer` (downsampled image) over the original rendering already in `frameBuffer`, wouldn't it?

--

Having setSize return a brand new buffer is really confusing. If you need to create a new buffer, do it with `new RenderBuffer(...`.

**Comment by SolarLune** [comment]
Fixed all of those. 

Thanks for the tip on leaving frameBuffer uncleared - I didn't want to add a new RenderBuffer, either, haha.

**Comment by GoranM** [comment]
We should probably shorten those long lines:

```java
int width = Gdx.graphics.getWidth() * filter.renderScale.x;
int height = Gdx.graphics.getHeight() * filter.renderScale.y;
if (tempBuffer.getWidth() != width || tempBuffer.getHeight() != height)
    tempBuffer = new RenderBuffer(spriteBatch, width, height);
```

**Comment by SolarLune** [comment]
Updated!

**Pull request merged**
