### PR TITLE
(#437) Joining functionality to reduce GL draw calls

### PR DESCRIPTION
**Pull request by rafcolson**

### CODE REVIEW

**Comment by GoranM** [comment]
You're using `materialTransformed()` in only one place, so it seems like you could just inline it, and annotate the block with a comment, like you did for other steps in `updateJoinedMesh()`.

--

The naming seems a bit confusing: You have a lot of variables with "material" in their name (or some shorthand for material, like "mat", or "mt"), but you're not really doing anything with materials.

You're working with mesh vertices, so your variable names should reflect that.

--

It's probably not a good idea to get vertex data from scene json, because that doesn't actually represent active data on the Model.

I think it would probably be best if you get that data directly from the actual Model reference, [like we do in SpriteAnim](https://github.com/GoranM/bdx/blob/master/src/com/nilunder/bdx/components/SpriteAnim.java#L206-L209).

**Comment by rafcolson** [comment]
PR updated. I've also added a ```RuntimeException``` as a guideline not to join more than 10922, or the maximum length of the short array would be exceeded.

Do notice that ```updateJoinedMesh()``` will also set all objects in ```joinedMeshObjects``` invisible, and that removing the joiner from the scene will set those to be visible. But removing objects from ```joinedMeshObjects``` wouldn't do that, so objects have to be set visible manually. I guess this is okay?

**Comment by SolarLune** [comment]
I think it might be best not to set visibility at all, since that's something the developer can do with not too much additional effort, and it's not something that makes too much sense (it's only when the function is run that the objects are hidden, not when they're added). It's a minor issue, though, so I don't care much either way. 

Great work in seeing this through!

**Comment by rafcolson** [comment]
I think I would agree that changing visibility shouldn't be done by the joiner itself, so I've changed that. I think @GoranM would think so too. PR updated.

**Pull request merged**
