### PR TITLE
Issue #105 - Normalize random.direction().

### PR DESCRIPTION
**Pull request by SolarLune**
Change random.direction to random.vector.

### CODE REVIEW

**Comment by GoranM** [comment]
While length is (logically) irrelevant for Random.direction, restricting the length of Random.vector to 1 doesn't really make sense - It's not a random vector if no two components can be greater than 1/sqrt(2).

It's ok for Random.direction to have that restriction, but it wouldn't make sense for Random.vector.

To remove the last commit, you can do: `git reset --hard HEAD~` (on this branch, of course).

**Comment by SolarLune** [comment]
OK, after some thought, I think I agree with you. Having two functions (one for a normalized vector (`direction`), and one for a random one (`vector`)) should be a happy medium.

**Comment by GoranM** [comment]
Ok, just make it into a single commit, please:

```
git reset --soft HEAD~
git commit --amend -m "Add Random.vector(); direction() returns unit vector (#105)."
```

**Comment by SolarLune** [comment]
I think that should do it.

**Comment by GoranM** [comment]
Did you leave the `Issue #105 ` prefix in there on purpose?

One reference is sufficient, and for things like suggestions, I would prefer the postfix reference: `(#105)`.

Running the exact commit command I specified above should make the message proper.

**Comment by SolarLune** [comment]
Ah, I didn't see that. My mistake.

**Pull request merged**
