### PR TITLE
AudioDevice for controlling playback of sounds and music.

### PR DESCRIPTION
**Pull request by SolarLune**

### CODE REVIEW

**Comment by SolarLune** [comment]
Hey, here's an attempt at making a device class for audio playback that allows for tweaking volume, panning, and pitch from a global location. Let me know what you think.

**Comment by GoranM** [comment]
I remember we discussed something along these lines in #154, but we didn't decide on a specific approach.

I think we should hash it out there before making a PR.

**Comment by SolarLune** [comment]
That sounds fine, yeah.

**Comment by SolarLune** [comment]
OK, PR updated.

**Comment by GoranM** [comment]
The changes to GameObject.java (the added import statements) don't provide shortcuts to the relevant objects on Bdx. I'm pretty sure you would need to create the relevant fields on GameObject, and then set them to existing audio object on Bdx.

You could do that, or you could just leave Bdx.sounds and music to point at Bdx.audio.sounds and Bdx.audio.music.

I think the latter would probably be a sufficient shortcut, while not breaking the existing API.

---

I can see that you're tracking currently playing music streams, but I don't see the code that tracks currently playing sounds streams.

Did I just miss it, or was it omitted for some reason?

---

I don't think higher level effects, like "fading", belong in the engine. If someone wants to change volume over time, in some specific way, that's their responsibility.

**Comment by SolarLune** [comment]
> The changes to GameObject.java (the added import statements) don't provide shortcuts to the relevant objects on Bdx. I'm pretty sure you would need to create the relevant fields on GameObject, and then set them to existing audio object on Bdx.

Yo, that's right - I was going to add shortcuts, but decided against it, as it added code for not that much of a payoff (in my mind). I missed it when I cleaned things up - my bad. PR updated to fix it.

> I can see that you're tracking currently playing music streams, but I don't see the code that tracks currently playing sounds streams.

> Did I just miss it, or was it omitted for some reason?

I would have tracked currently playing sound streams, but it's not possible to tell when a sound stream is finished playing. I could alter looping sound streams, since they won't stop unless the developer interjects, but already playing sound streams could be looped after initial play, or, conversely, looping sounds could be set to not loop after starting. So, I'd need to keep track of both playing and looping streams just to adjust looping sound streams. 

That was so much work and additional code that I just ended up omitting automatic live adjustment of sounds - sounds only alter their properties on first play, which isn't a huge deal (since you won't generally dynamically, in-game, alter global sound playback properties).

> I don't think higher level effects, like "fading", belong in the engine. If someone wants to change volume over time, in some specific way, that's their responsibility.

I would generally agree for high level effects, but fading a BGM in and out is fairly common in games and extremely useful, so I feel like it's a key usability feature.

**Comment by GoranM** [comment]
There is also a fairly common need for sprite animation, but we don't encode that feature directly into the engine core, because sprite animation is simply the manipulation of texture coordinates, and that makes it a higher level feature that can be encoded in a component.

We ship a default implementation of that component not just because there's a fairly common need for the feature, but also because the implementation is not trivial, and therefore not something that people could easily write on their own.

Fade, on the other hand, is simply manipulating a single value (volume) over time, and typically in a linear fashion, so I think one would have to stretch to justify inclusion even as a component, let alone engine code.

**Comment by SolarLune** [comment]
> the implementation is not trivial, and therefore not something that people could easily write on their own.

I see what you mean, but we have other components that are fairly trivial to write, like the Halo and Track components. The component and state classes themselves are also very simple. I don't think "it's hard to write on your own" should be the qualifier for whether a particular piece of code is implemented into the engine or not - I think it should be whether it would be useful to most users. 

I don't mind too much moving fading into a component, but I feel like it's useful enough and utilized in enough games to justify inclusion somehow.

**Comment by GoranM** [comment]
Track and Halo mostly serve as familiar examples for how one could write basic components. They don't represent a baseline for inclusion.

The component and state classes are engine-level abstractions that provide the foundation for writing components, so I don't see how their simplicity relates to what we're discussing here.

I'm not arguing that implementation effort should be the only metric for component inclusion, but I think it should be a factor, because we don't want to clutter the engine with components that do overly trivial things (ie: incrementing/decrementing a value).

For now, I think it would be best if you make the fade component a part of your helper library. That way, if anyone wants to use it, it's available, and if there are more users, and most of them want to use it, we can make it a default that ships with the engine.

**Comment by SolarLune** [comment]
Fair enough.

PR updated.

**Comment by GoranM** [comment]
Instead of an update method that has to run in the main engine loop, on each frame, you could simply have setters that would update playing streams.

---

Considering that you're already looping through all elements in playingMusic, and removing those that are not currently playing, it seems redundant to also remove them in pause and stop methods.

**Comment by SolarLune** [comment]
Ah, I missed those points. Fixed.

**Comment by GoranM** [comment]
I don't think we need to run an update method on every frame.

The list of tracked streams doesn't have to be exclusively a list of currently playing streams, as long as those are included, so I think it's probably sufficient to remove non playing streams in the play method.

**Comment by SolarLune** [comment]
OK, I think I got it - I updated it again.

**Pull request merged**
